
server:
  port: 0

spring:
  application:
    name: order-service
  jpa:
    hibernate:
#      ddl-auto: validate #update create-update validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    database: mysql
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/micro?serverTimezone=Asia/Seoul
    username: root
    password: 190711
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://127.0.0.1:9411/
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: welcome to the simple e-commerce

logging:
  level:
    com.example.com.example.orderservice: debug