
server:
  port: 8888

spring:
  application:
    name: microservice
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/eunchanyang/Desktop/java/yml-only
        git:
          uri: https://github.com/yangddoddi/microservice.git
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  config:
    import:
      - classpath:/bootstrap.yml