
server:
  port: 0

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update #update create-update validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    database: mysql
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/micro?serverTimezone=Asia/Seoul
    username: root
    password: 190711
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: welcome to the simple e-commerce