server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
#  ?? ??? ?? ??????? ??? ??? ??? ? ??
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh